# Generated by Django 5.2 on 2025-04-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='meeting_schedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
