# Generated by Django 5.2 on 2025-04-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0003_trip_meeting_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="recommendations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
