# Generated by Django 5.2 on 2025-04-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_latitude_trip_longitude_trip_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('packing_requirements', models.TextField(default='[]')),
                ('weather_considerations', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='CulturalInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('traveler_type', models.CharField(choices=[('casual', 'Casual Traveler'), ('business', 'Business Traveler')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TravelTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('business', 'Business'), ('cultural', 'Cultural'), ('safety', 'Safety'), ('transportation', 'Transportation')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('traveler_type', models.CharField(choices=[('casual', 'Casual Traveler'), ('business', 'Business Traveler')], max_length=10)),
                ('destination', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='calendar_integration',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='trip',
            name='calendar_integration',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cultural_insights',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='trip',
            name='travel_tips',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='trip',
            name='traveler_type',
            field=models.CharField(choices=[('casual', 'Casual Traveler'), ('business', 'Business Traveler')], default='casual', max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='activities',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='meeting_schedule',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='packing_list',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='recommendations',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('accessories', 'Accessories'), ('electronics', 'Electronics'), ('toiletries', 'Toiletries'), ('documents', 'Documents'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_essential', models.BooleanField(default=False)),
                ('weather_conditions', models.TextField(default='[]')),
                ('activity_requirements', models.ManyToManyField(blank=True, to='trips.activity')),
            ],
        ),
    ]
